// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgs29SUqHBJ4DXO1W0CSWoe0Tv1Qw9lls',
    appId: '1:428625357631:web:7ef453922d18b55e6b418a',
    messagingSenderId: '428625357631',
    projectId: 'farmacia-app01',
    authDomain: 'farmacia-app01.firebaseapp.com',
    storageBucket: 'farmacia-app01.appspot.com',
    measurementId: 'G-VRHW90ZCHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccl-W2zCzWTUPgboNAvVOWWxf2_5v_kM',
    appId: '1:428625357631:android:b48edcf3f36db30f6b418a',
    messagingSenderId: '428625357631',
    projectId: 'farmacia-app01',
    storageBucket: 'farmacia-app01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuOV_XPQUiOtMe6PXZuzU_ubU7PtHrju0',
    appId: '1:428625357631:ios:04686b3487d9f6b16b418a',
    messagingSenderId: '428625357631',
    projectId: 'farmacia-app01',
    storageBucket: 'farmacia-app01.appspot.com',
    iosClientId:
        '428625357631-tsbtf257ndgi2ca44jp880i56i1e3504.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuOV_XPQUiOtMe6PXZuzU_ubU7PtHrju0',
    appId: '1:428625357631:ios:04686b3487d9f6b16b418a',
    messagingSenderId: '428625357631',
    projectId: 'farmacia-app01',
    storageBucket: 'farmacia-app01.appspot.com',
    iosClientId:
        '428625357631-tsbtf257ndgi2ca44jp880i56i1e3504.apps.googleusercontent.com',
    iosBundleId: 'com.example.bioFarm',
  );
}
